#when it happens
on: 
  push:
    branches:
      - main
  workflow_dispatch: #when we click

#what it does
jobs:
  quality_check:
    name: "Quality Check"
    runs-on: ubuntu-latest
    steps:
      #get access to repo code
      - name: "Get repo"
        uses: actions/checkout@v6
      #install python
      - name: "Install python"
        uses: actions/setup-python@v6
      #install relevant libraries
      - name: "Install libraries"
        run: pip install -r requirements.txt
      #run pytest/pylint
      - name: "Run pytest"
        run: pytest

    
